# Generated by Django 5.1.5 on 2025-03-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('numero_bta', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('etat_matrimonial', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf')], max_length=50)),
                ('adresse', models.TextField()),
                ('nom_pere', models.CharField(max_length=255)),
                ('nom_mere', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_entree', models.DateField()),
                ('source_orientation', models.CharField(max_length=255)),
                ('raison_direction', models.TextField()),
                ('suite_couchage', models.CharField(blank=True, max_length=100, null=True)),
                ('chambre', models.CharField(blank=True, max_length=50, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('raison_depart', models.TextField(blank=True, null=True)),
                ('son_compagnon', models.CharField(blank=True, max_length=255, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('lieu_deces', models.CharField(blank=True, max_length=255, null=True)),
                ('handicap_moteur', models.BooleanField(default=False)),
                ('sourd_muet', models.BooleanField(default=False)),
                ('deficience_visuelle', models.BooleanField(default=False)),
                ('handicap_gras', models.BooleanField(default=False)),
                ('membres_amputes', models.BooleanField(default=False)),
                ('maladie_mentale', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('pression_arterielle', models.BooleanField(default=False)),
                ('tumeurs', models.BooleanField(default=False)),
                ('tuberculose', models.BooleanField(default=False)),
            ],
        ),
    ]
