# Generated by Django 5.1.5 on 2025-03-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='numero_bta',
            new_name='Cin',
        ),
    ]
