# Generated by Django 5.1.5 on 2025-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_rename_numero_bta_patient_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
