# Generated by Django 5.1.5 on 2025-03-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_alter_patient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='etat_matrimonial',
        ),
    ]
