# Generated by Django 5.1.5 on 2025-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_remove_patient_etat_matrimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='etat_matrimonial',
            field=models.CharField(blank=True, choices=[('Célibataire', 'عازب'), ('Marié', 'متزوج'), ('Divorcé', 'مطلق'), ('Veuf', 'أرمل')], max_length=50, null=True),
        ),
    ]
