# Generated by Django 5.1.5 on 2025-03-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_patient_etat_matrimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='suite_couchage',
            field=models.CharField(blank=True, choices=[('جناح الرجال', 'جناح الرجال'), ('جناح النساء', 'جناح النساء'), ('البنايات الجديدة رجال', 'البنايات الجديدة رجال'), ('العمارات', 'العمارات')], max_length=100, null=True),
        ),
    ]
