# Generated by Django 5.1.5 on 2025-03-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_alter_patient_suite_couchage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10),
        ),
    ]
