# Generated by Django 5.1.5 on 2025-03-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_alter_patient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='handicap_gras',
        ),
    ]
