# Generated by Django 5.1.5 on 2025-03-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_alter_patient_deficience_visuelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
    ]
