# Generated by Django 5.1.5 on 2025-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_alter_patient_date_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, null=True),
        ),
    ]
