# Generated by Django 5.1.5 on 2025-03-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0013_alter_patient_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hopital', models.CharField(max_length=255)),
                ('date_admission', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.patient')),
            ],
        ),
    ]
