# Generated by Django 5.1.5 on 2025-03-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_hospitalisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospitalisation',
        ),
    ]
